In [45]:
import pandas as pd
import numpy as np
import json

In [46]:
easy = 'arc_easy.json'
with open(easy) as train_file:
    dez = json.load(train_file)

In [47]:
df_easy = pd.DataFrame(dez)
df_easy["answer"][0][0]

'Sunlight is the source of energy for nearly all ecosystems.'

In [48]:
import re

def get_correct_choice_label(question_str, answer):
    """
    Given a question string with choices and the correct answer,
    returns the corresponding choice label (e.g., 'B' or '2').
    Works for both lettered and numbered labels.
    """
    if type(answer) == list:
        answer = answer[0]
    # Extract the part after "Choices:"
    match = re.search(r"Choices:\s*(.*)", question_str)
    if not match:
        return None

    choices_part = match.group(1)
    # Split choices and strip spaces
    choices = [c.strip() for c in choices_part.split('|')]

    for choice in choices:
        # Match labels that are letters or numbers before a period
        label_match = re.match(r"([A-Za-z0-9]+)\.\s*(.*)", choice)
        if label_match:
            label, text = label_match.groups()
            # Normalize and compare answer text
            if text.strip().lower() == answer.strip().lower():
                return label.lower()

    return None

In [49]:
def cleandf(df):
    accdf = df[['question', 'answer', 'rewrite_all_ans']]
    if type(accdf['answer'][0]) == list:
        accdf =  accdf.assign(answer = accdf['answer'].apply(lambda x: x[0]))
    accdf = accdf.assign(answer_letter = df.apply(lambda r: get_correct_choice_label(r["question"], r['answer']), axis = 1))
    return accdf

In [59]:
def get_accc(row):
    correct = row['answer'].lower()
    correct = re.sub(r'[^a-zA-Z0-9\s]+', '', correct)
    correct_letter = row['answer_letter']
    out = [0,0]
    lst = row['rewrite_all_ans']
    for l in lst:
        for ans in l:
            if correct in ans or ans == correct_letter or ans == f'boxed{correct_letter}':
                out[0] = out[0] + 1
            out[1] = out[1] + 1
    return out

In [60]:
df_easy

,question,answer,rewrite_all_ans,answer_letter
0,Which statement best explains why photosynthes...,Sunlight is the source of energy for nearly al...,[[sunlight is source of energy for nearly all ...,a
1,Which piece of safety equipment is used to kee...,breathing mask,"[[b, boxedb, b, boxedb, b, b, b, b, b, boxedb]...",b
2,Meiosis is a type of cell division in which ge...,ovary cells,"[[d, d, d, d, d, d, d, d, d, d], [boxedd, d, d...",d
3,Which characteristic describes the texture of ...,soft,"[[boxedd, boxedd, boxedd, boxedd, boxedd, boxe...",d
4,Which best describes the structure of an atom?...,a massive core surrounded by negatively-charge...,"[[boxedb, b, b, boxedb, boxedb, b, boxedb, box...",b
5,To express the distance between the Milky Way ...,light-year.,"[[c, c, c, c, boxedc, boxedc, c, boxedc, c, bo...",c
6,A student has just completed a laboratory acti...,wash hands,"[[boxedb, d, boxedb, d, b, to determine correc...",a
7,Students are investigating the effects of diff...,grams,"[[boxedc, boxedc, c, boxedc, c, boxedc, boxedc...",c
8,Plants use sunlight to make\nChoices: A. soil....,food.,"[[boxedc, boxedc, boxedc, boxedc, c, c, boxedc...",c
9,Which of these correctly identifies the way ma...,Xylem carries water from the roots to the leaves.,"[[, boxeda, boxeda, boxeda, boxeda, boxeda, bo...",a
10,"When trees develop leaves in the spring, 10 ch...",Sunlight is reduced.,"[[boxeda, to solve this task lets break down i...",b
11,The circulatory system and the endocrine syste...,releasing hormones and transporting them to ce...,"[[boxedb, boxedb, boxedb, boxedb, boxedb, boxe...",b
12,A student throws a ball into the air. While th...,gravity,"[[boxedb, boxedb, b, boxedb, boxedb, b, b, box...",b
13,Which of these will most likely harm a habitat...,water pollution,"[[boxedb, boxedb, boxedb, boxedb, b, boxedb, b...",b
14,All living and nonliving material is composed ...,elements,NaN,2
15,Which process best explains how the Grand Cany...,erosion,"[[boxedb, boxedb, boxedb, boxedb, boxedb, boxe...",b
16,"As global temperatures increase, certain organ...",fish that live in coral reefs in shallow waters,"[[b, b, boxedb, boxeda, b, b, boxedb, b, boxed...",b
17,A dish of sugar water was left on a window sil...,the water evaporated.,"[[d, d, d water evaporated explanation presenc...",d
18,Using a softball bat to hit a softball is an e...,lever,"[[b, b, boxedb, boxedb, boxedb, boxedb, b, box...",b
19,When an igneous intrusion comes into contact w...,recrystallize.,"[[boxedb, b, boxedb, b, boxedb, boxedb, boxedb...",d
20,A research scientist writes a paper on the ini...,Secondary Succession,"[[boxedd, boxedd, boxedd, boxedd, boxedd, boxe...",d
21,Where do plants get most of the energy they ne...,sunlight,"[[boxedd, boxedd, boxedd, boxedd, boxedd, boxe...",d
22,Which is a statement about climate?\nChoices: ...,The average high temperature in May is 20°C.,"[[boxedd, boxedd, boxedd, d, boxedd, d, boxedd...",d
23,"While on a movie set, a stuntman jumps off the...",kinetic energy,"[[boxedc, boxedc, boxedc, boxedc, boxedc, boxe...",c
24,Jessica wants to see cells in an oak tree leaf...,microscope,"[[boxedb, boxedb, boxedb, boxedb, boxedb, b mi...",b
25,Biologists conduct investigations to learn abo...,designing an investigation with repeated trial...,"[[boxedc, boxedc, boxedc, boxedc, boxedc, c, b...",c
26,Which factor is most likely to cause the numbe...,fewer predators,"[[boxed2, boxed2, boxed2, boxed2, boxed2, boxe...",2
27,Seeds that remain inactive until the right con...,dormant,"[[boxedb, boxedb, b, boxedb, b, to solve this ...",b
28,What allows a light bulb to give off light?\nC...,the current flowing through the wire to the li...,"[[boxeda, , boxeda, boxeda, , , boxeda, , , c]...",a
29,What causes sound?\nChoices: A. sunlight | B. ...,vibrations,"[[boxedb, boxedb, boxedb, b, boxedb, boxedb, b...",b
30,Photosynthesis occurs in which of these organi...,Sunflower plant,"[[, boxeda, boxeda, boxeda, , boxeda, boxeda, ...",a
31,"In order for cells to grow at a normal rate, t...",take in nutrients.,"[[boxedc, c, boxedc, boxedc, c, boxedc, c, box...",c
32,Marshall learned that plants need a substance ...,carbon dioxide,"[[boxeda, boxeda, boxeda, , , , boxeda, , boxe...",a
33,Antarctica is a continent at Earth's south pol...,"Millions of years ago, Antarctica was in a war...","[[boxeda, boxeda, , , boxeda, boxeda, boxedd, ...",a
34,Which two theories of Moon formation propose t...,The Fission Theory and the Giant Impact Theory,"[[c, c fission theory and giant impact theory,...",c
35,"When white, fluffy clouds appear in Massachuse...",fair.,"[[boxeda, boxeda, boxeda, , , , boxeda, , , bo...",a
36,Plants and animals are composed of organic com...,"carbon, hydrogen, oxygen, nitrogen.","[[d, boxedd, d carbon hydrogen oxygen nitrogen...",d
37,New research uncovers information that proves ...,use the new information to update the old theory,"[[boxedc, boxedc, boxedc, boxedc, boxedc, boxe...",c
38,Which is the greatest benefit of sexual reprod...,ability to produce genetically different offsp...,"[[c, boxedc, boxedc, boxedc, boxedc, boxedc, b...",c
39,The speed at which sound waves travel depends ...,type of material through which the sound travels.,"[[boxedb, boxedb, boxedb, boxedb, boxedb, b, b...",b

In [61]:
df_easy = cleandf(df_easy)
df_easy

,question,answer,rewrite_all_ans,answer_letter
0,Which statement best explains why photosynthes...,Sunlight is the source of energy for nearly al...,[[sunlight is source of energy for nearly all ...,a
1,Which piece of safety equipment is used to kee...,breathing mask,"[[b, boxedb, b, boxedb, b, b, b, b, b, boxedb]...",b
2,Meiosis is a type of cell division in which ge...,ovary cells,"[[d, d, d, d, d, d, d, d, d, d], [boxedd, d, d...",d
3,Which characteristic describes the texture of ...,soft,"[[boxedd, boxedd, boxedd, boxedd, boxedd, boxe...",d
4,Which best describes the structure of an atom?...,a massive core surrounded by negatively-charge...,"[[boxedb, b, b, boxedb, boxedb, b, boxedb, box...",b
5,To express the distance between the Milky Way ...,light-year.,"[[c, c, c, c, boxedc, boxedc, c, boxedc, c, bo...",c
6,A student has just completed a laboratory acti...,wash hands,"[[boxedb, d, boxedb, d, b, to determine correc...",a
7,Students are investigating the effects of diff...,grams,"[[boxedc, boxedc, c, boxedc, c, boxedc, boxedc...",c
8,Plants use sunlight to make\nChoices: A. soil....,food.,"[[boxedc, boxedc, boxedc, boxedc, c, c, boxedc...",c
9,Which of these correctly identifies the way ma...,Xylem carries water from the roots to the leaves.,"[[, boxeda, boxeda, boxeda, boxeda, boxeda, bo...",a
10,"When trees develop leaves in the spring, 10 ch...",Sunlight is reduced.,"[[boxeda, to solve this task lets break down i...",b
11,The circulatory system and the endocrine syste...,releasing hormones and transporting them to ce...,"[[boxedb, boxedb, boxedb, boxedb, boxedb, boxe...",b
12,A student throws a ball into the air. While th...,gravity,"[[boxedb, boxedb, b, boxedb, boxedb, b, b, box...",b
13,Which of these will most likely harm a habitat...,water pollution,"[[boxedb, boxedb, boxedb, boxedb, b, boxedb, b...",b
14,All living and nonliving material is composed ...,elements,NaN,2
15,Which process best explains how the Grand Cany...,erosion,"[[boxedb, boxedb, boxedb, boxedb, boxedb, boxe...",b
16,"As global temperatures increase, certain organ...",fish that live in coral reefs in shallow waters,"[[b, b, boxedb, boxeda, b, b, boxedb, b, boxed...",b
17,A dish of sugar water was left on a window sil...,the water evaporated.,"[[d, d, d water evaporated explanation presenc...",d
18,Using a softball bat to hit a softball is an e...,lever,"[[b, b, boxedb, boxedb, boxedb, boxedb, b, box...",b
19,When an igneous intrusion comes into contact w...,recrystallize.,"[[boxedb, b, boxedb, b, boxedb, boxedb, boxedb...",d
20,A research scientist writes a paper on the ini...,Secondary Succession,"[[boxedd, boxedd, boxedd, boxedd, boxedd, boxe...",d
21,Where do plants get most of the energy they ne...,sunlight,"[[boxedd, boxedd, boxedd, boxedd, boxedd, boxe...",d
22,Which is a statement about climate?\nChoices: ...,The average high temperature in May is 20°C.,"[[boxedd, boxedd, boxedd, d, boxedd, d, boxedd...",d
23,"While on a movie set, a stuntman jumps off the...",kinetic energy,"[[boxedc, boxedc, boxedc, boxedc, boxedc, boxe...",c
24,Jessica wants to see cells in an oak tree leaf...,microscope,"[[boxedb, boxedb, boxedb, boxedb, boxedb, b mi...",b
25,Biologists conduct investigations to learn abo...,designing an investigation with repeated trial...,"[[boxedc, boxedc, boxedc, boxedc, boxedc, c, b...",c
26,Which factor is most likely to cause the numbe...,fewer predators,"[[boxed2, boxed2, boxed2, boxed2, boxed2, boxe...",2
27,Seeds that remain inactive until the right con...,dormant,"[[boxedb, boxedb, b, boxedb, b, to solve this ...",b
28,What allows a light bulb to give off light?\nC...,the current flowing through the wire to the li...,"[[boxeda, , boxeda, boxeda, , , boxeda, , , c]...",a
29,What causes sound?\nChoices: A. sunlight | B. ...,vibrations,"[[boxedb, boxedb, boxedb, b, boxedb, boxedb, b...",b
30,Photosynthesis occurs in which of these organi...,Sunflower plant,"[[, boxeda, boxeda, boxeda, , boxeda, boxeda, ...",a
31,"In order for cells to grow at a normal rate, t...",take in nutrients.,"[[boxedc, c, boxedc, boxedc, c, boxedc, c, box...",c
32,Marshall learned that plants need a substance ...,carbon dioxide,"[[boxeda, boxeda, boxeda, , , , boxeda, , boxe...",a
33,Antarctica is a continent at Earth's south pol...,"Millions of years ago, Antarctica was in a war...","[[boxeda, boxeda, , , boxeda, boxeda, boxedd, ...",a
34,Which two theories of Moon formation propose t...,The Fission Theory and the Giant Impact Theory,"[[c, c fission theory and giant impact theory,...",c
35,"When white, fluffy clouds appear in Massachuse...",fair.,"[[boxeda, boxeda, boxeda, , , , boxeda, , , bo...",a
36,Plants and animals are composed of organic com...,"carbon, hydrogen, oxygen, nitrogen.","[[d, boxedd, d carbon hydrogen oxygen nitrogen...",d
37,New research uncovers information that proves ...,use the new information to update the old theory,"[[boxedc, boxedc, boxedc, boxedc, boxedc, boxe...",c
38,Which is the greatest benefit of sexual reprod...,ability to produce genetically different offsp...,"[[c, boxedc, boxedc, boxedc, boxedc, boxedc, b...",c
39,The speed at which sound waves travel depends ...,type of material through which the sound travels.,"[[boxedb, boxedb, boxedb, boxedb, boxedb, b, b...",b

In [62]:

accs = df_easy.apply(get_accc, axis = 1)
total = 0
s = 0
for i in accs:
    s = s + i[0]
    total = total + i[1]
s/total

TypeError: 'float' object is not iterable

In [63]:
chall = 'challenging.json'
with open(chall) as train_file:
    chal = json.load(train_file)
df_chall = pd.DataFrame(chal)

In [64]:
df_chall

,question,answer,answer_norm,rewrite_all_ans,pred_ans,pred_ans_mv_over_rewrites,is_correct,prop,data_uncertainty,total_uncertainty,model_uncertainty_list,isambig
0,An astronomer observes that a planet rotates f...,Planetary days will become shorter.,[c],"[[boxedc, c, c planetary days will become shor...",boxedc,boxedc,False,0.349096,1.306830,3.743465,"[2.3219281566334526, 2.0464394101813363, 1.770...",False
1,A group of engineers wanted to know how differ...,buildings will be made safer,[b],[[b buildings will be made safer this outcome ...,b buildings will be made safer this outcome is...,b buildings will be made safer this outcome is...,False,0.411408,2.321928,5.643856,"[3.3219282202475524, 3.3219282202475524, 3.321...",False
2,The end result in the process of photosynthesi...,Chlorophyll in the leaf captures light energy.,[c],"[[c, c chlorophyll in leaf captures light ener...",c,c,False,0.416249,2.106830,5.061468,"[3.3219281889075054, 3.3219281889075054, 3.121...",False
3,A physicist wants to determine the speed a car...,the independent (manipulated) variable,[d],"[[d, d independent manipulated variable in exp...",d,d,False,0.390377,1.912640,4.899471,"[2.846439443521073, 3.121928189587505, 2.52192...",False
4,An astronaut drops a 1.0 kg object and a 5.0 k...,They have each gained one-half of their maximu...,[d],[[answer d astronauts object has greater mass ...,boxedd,boxedd,False,0.368401,1.271287,3.450827,"[2.846439386253108, 2.6464393897071123, 0.9219...",False
5,Devil facial tumor disease (DFTD) is a disease...,"an infectious, cell-cycle disease",[b],[[to answer this question correctly we need to...,b,b,False,0.414945,1.855545,4.471789,"[3.321928176371486, 3.321928176371486, 3.12192...",False
6,A type of small mammal from the mountain regio...,to store food that will be eaten over the wint...,[c],[[d to protect grasses and seeds from decay be...,c,d to protect grasses and seeds from decay befo...,False,0.407207,2.281928,5.603856,"[3.321928217113548, 3.321928217113548, 3.32192...",False
7,Petrified palm trees are found in sedimentary ...,The climate in the area was once tropical.,[c],"[[boxedc, c, boxedc, boxedc, c, c, c, c this c...",c,c,False,0.426395,1.866830,4.378172,"[1.2954619411921595, 1.2954619411921595, 3.321...",False
8,Farmers in Wyoming were concerned because some...,Populations of mice and rats would increase.,[b],[[c heres why if hawks are removed from area i...,c,c heres why if hawks are removed from area its...,False,0.414345,2.321928,5.603856,"[3.321928217113548, 3.321928217113548, 3.12192...",False
9,Copper is an element that is used in electrica...,the atom,[],[[atom at microscopic level smallest unit of m...,,atom,False,0.400288,1.838632,4.593270,"[2.8464394307948586, 2.160964142161001, 3.1219...",False
10,"According to cell classification, prokaryotic ...",size differences,[b],[[b size differences explanation prokaryotic c...,b size differences,b size differences,False,0.390604,2.017026,5.163856,"[3.32192819830952, 3.32192819830952, 3.1219282...",False
11,Which statement best describes the effect of t...,The Sun influences the formation of waves.,[],[[sun influences formation of waves this optio...,sun influences formation of waves,sun influences formation of waves this option ...,False,0.414345,2.321928,5.603856,"[3.321928217113548, 3.321928217113548, 3.32192...",False
12,The morning temperature in a city is 41Â°F. If...,78Â° F,[c],[[c 78Â°f explanation morning temperature is 4...,c,c,False,0.369893,1.697542,4.589275,"[3.321928170103477, 3.321928170103477, 3.12192...",False
13,A class plans an investigation to see which br...,Make a table for recording data.,[c],[[d make daily observations of light bulbs pri...,d,d,False,0.385519,1.814246,4.705979,"[2.5219281852394952, 2.846439430794859, 2.6464...",False
14,Which of these gases is the most abundant gree...,water vapor,[c],[[c water vapor water vapor is most abundant g...,boxedc,boxedc,False,0.436553,1.365923,3.128884,"[2.160964086909281, 2.521928130601415, 2.16096...",False
15,At which temperature does water freeze?\nChoic...,0 degrees Celsius,[],[[0 degrees celsius this is standard freezing ...,0 degrees celsius,0 degrees celsius,False,0.423788,1.707716,4.029644,"[0.9219281931535007, 3.3219281638354676, 0.921...",False
16,Fossil bones and teeth of dinosaurs have been ...,analyze new data as it becomes available,[c],[[c analyze new data as it becomes available w...,c analyze new data as it becomes available,c analyze new data as it becomes available,False,0.335442,1.220485,3.638432,"[2.1609640934094827, 1.7709506443081988, 3.321...",False
17,Molly was making iced tea by putting tea bags ...,from the tea to the ice,[b],[[b from tea to ice heres why when molly pours...,b,b,False,0.449391,0.938906,2.089284,"[3.121928113891391, 4.852676648463973e-08, 4.8...",False
18,Logging companies cut trees in a forest and se...,the price of boards will increase,[],[[b price of boards will decrease explanation ...,,b price of boards will decrease explanation lo...,False,0.410134,2.281928,5.563856,"[3.321928213979543, 3.321928213979543, 3.32192...",False
19,It was once thought that living organisms coul...,continued experimentation.,[c],[[d invention of microscope before invention o...,d invention of microscope,d invention of microscope before invention of ...,False,0.401320,2.226830,5.548758,"[3.321928213979543, 3.321928213979543, 3.32192...",False
20,Cells take in food for energy. The part of the...,breaking down wastes,[b],[[b breaking down wastes lysosomes are respons...,b breaking down wastes,b breaking down wastes,False,0.425084,1.984833,4.669275,"[3.321928176371486, 3.321928176371486, 1.77095...",False
21,When an electric current is passed through wat...,2H_{2}O(l) -> 2H_{2}(g) + O_{2}(g),[b],[[answer b reasoning skill identifying pros an...,b,b,False,0.380557,1.234176,3.243074,"[2.3219281501654434, 2.5219281466714385, 2.921...",False
22,Which is a fact about penguins?\nChoices: A. P...,Penguins can live in climates with freezing te...,[],"[[, penguins can live in climates with freezin...",,,False,0.411408,2.321928,5.643856,"[3.3219282202475524, 3.3219282202475524, 3.321...",False
23,A glass of water at 110Â°F is placed in a room...,73Â°F.,[c],"[[c, c, c, c, c, boxed73, boxed73, c, c, c], [...",c,boxed73,False,0.355194,1.266713,3.566253,"[0.721928162887458, 1.9609641033836904, 2.3709...",False
24,"Snow, rain, hail, and fog are all forms of\nCh...",water.,[b],[[b water all forms of snow rain hail and fog ...,b,b water all forms of snow rain hail and fog ar...,False,0.460228,2.184833,4.747278,"[3.3219281795054916, 3.3219281795054916, 2.846...",False
25,Scott filled a tray with juice and put it in a...,It became a solid.,[d],[[d it became solid explanation scott filled t...,d,d it became solid explanation scott filled tra...,False,0.407207,2.281928,5.603856,"[3.321928217113548, 3.321928217113548, 3.32192...",False
26,"On August 21, a flash flood warning was issued...",It is a seasonal weather feature with irregula...,[b],[[d it is rare event inconsistent with local c...,d,d it is rare event inconsistent with local cli...,False,0.408615,2.201928,5.388758,"[3.321928204577529, 3.321928204577529, 3.32192...",False
27,Students heated three objects to different tem...,"Object 1, Object 3, Object 2",[b],"[[boxedb, to answer this question we need to u...",boxedb,boxedb,False,0.348832,1.244762,3.568367,"[1.3567797065711968, 2.446439393161117, 2.6464...",False
28,Tiny organisms called plankton live in oceans....,Plankton release oxygen.,[c],[[c plankton release oxygen explanation plankt...,c plankton release oxygen explanation plankton...,c plankton release oxygen explanation plankton...,False,0.411408,2.321928,5.643856,"[3.3219282202475524, 3.3219282202475524, 3.321...",False
29,Which statement best explains why a tree branc...,Wood is buoyant.,[b],[[wood is porous explanation reason tree branc...,wood is porous,wood is porous explanation reason tree branch ...,False,0.407207,2.281928,5.603856,"[3.321928217113548, 3.321928217113548, 3.32192...",False
30,Students are observing two fossils in a lab. T...,the type of environment in which the organisms...,[d],[[d type of environment in which organisms liv...,d type of environment in which organisms lived...,d type of environment in which organisms lived...,False,0.411408,2.321928,5.643856,"[3.3219282202475524, 3.3219282202475524, 3.321...",False
31,Earth's distance from the Sun enables water to...,its ability to exist as a liquid,[c],"[[c its ability to exist as liquid, c its abil...",c,c,False,0.420261,1.967276,4.681077,"[3.1219281769714864, 1.3567797531984713, 3.321...",False
32,Which statement correctly describes a property...,Air is a mixture of gases.,[],[[air is mixture of gases explanation this cho...,b,air is mixture of gases explanation this choic...,False,0.403947,2.186830,5.413661,"[3.321928204577529, 3.321928204577529, 3.32192...",False
33,Which statement describes a positive effect of...,It helps explain how things work.,[c],[[c it helps explain how things work this choi...,c it helps explain how things work,c it helps explain how things work this choice...,False,0.422278,2.281928,5.403856,"[3.321928204577529, 3.321928204577529, 3.12192...",False
34,Which natural event occurs with the most frequ...,sunrise,[],"[[answer, step 1 problem explanation problem a...",,,False,0.411118,2.224833,5.411663,"[3.121928211665539, 2.8464394657919487, 3.3219...",False
35,A scientist maps a long region in which earthq...,Volcanism also characterizes the region.,[],[[c region shows extensive faulting of sedimen...,d,d,False,0.403621,2.129735,5.276566,"[3.1219282022035246, 3.32192819830952, 3.32192...",False
36,Which best describes how the sun might compare...,The sun would be tiny next to one of the large...,[b],"[[b, b, b sun would be tiny next to one of lar...",b,b sun would be tiny next to one of largest stars,False,0.360744,1.478257,4.097797,"[2.3219281728034766, 2.9219281648354674, 2.370...",False
37,Which statement is true about the solar system...,The solid planets are closer to the Sun.,[b],[[b solid planets are closer to sun explanatio...,b solid planets are closer to sun,b solid planets are closer to sun,False,0.398390,2.146830,5.388758,"[3.321928204577529, 3.321928204577529, 3.12192...",False
38,What is the main function of photosynthetic ce...,to convert energy from sunlight into food energy,[c],[[c to convert energy from sunlight into food ...,c to convert energy from sunlight into food en...,c to convert energy from sunlight into food en...,False,0.411408,2.321928,5.643856,"[3.3219282202475524, 3.3219282202475524, 3.321...",False
39,Which of the following is the primary differen...,Hydraulic systems involve liquids and pneumati...,[b],[[b hydraulic systems involve liquids and pneu...,hydraulic systems are under pressure and pneum...,b hydraulic systems involve liquids and pneuma...,False,0.414345,2.321928,5.603856,"[3.321928217113548, 3.1219282211275527, 3.3219...",False

In [65]:
dftogetchal = cleandf(df_chall)

In [66]:
dftogetchal

,question,answer,rewrite_all_ans,answer_letter
0,An astronomer observes that a planet rotates f...,Planetary days will become shorter.,"[[boxedc, c, c planetary days will become shor...",c
1,A group of engineers wanted to know how differ...,buildings will be made safer,[[b buildings will be made safer this outcome ...,b
2,The end result in the process of photosynthesi...,Chlorophyll in the leaf captures light energy.,"[[c, c chlorophyll in leaf captures light ener...",c
3,A physicist wants to determine the speed a car...,the independent (manipulated) variable,"[[d, d independent manipulated variable in exp...",d
4,An astronaut drops a 1.0 kg object and a 5.0 k...,They have each gained one-half of their maximu...,[[answer d astronauts object has greater mass ...,d
5,Devil facial tumor disease (DFTD) is a disease...,"an infectious, cell-cycle disease",[[to answer this question correctly we need to...,b
6,A type of small mammal from the mountain regio...,to store food that will be eaten over the wint...,[[d to protect grasses and seeds from decay be...,c
7,Petrified palm trees are found in sedimentary ...,The climate in the area was once tropical.,"[[boxedc, c, boxedc, boxedc, c, c, c, c this c...",c
8,Farmers in Wyoming were concerned because some...,Populations of mice and rats would increase.,[[c heres why if hawks are removed from area i...,b
9,Copper is an element that is used in electrica...,the atom,[[atom at microscopic level smallest unit of m...,a
10,"According to cell classification, prokaryotic ...",size differences,[[b size differences explanation prokaryotic c...,b
11,Which statement best describes the effect of t...,The Sun influences the formation of waves.,[[sun influences formation of waves this optio...,a
12,The morning temperature in a city is 41Â°F. If...,78Â° F,[[c 78Â°f explanation morning temperature is 4...,c
13,A class plans an investigation to see which br...,Make a table for recording data.,[[d make daily observations of light bulbs pri...,c
14,Which of these gases is the most abundant gree...,water vapor,[[c water vapor water vapor is most abundant g...,c
15,At which temperature does water freeze?\nChoic...,0 degrees Celsius,[[0 degrees celsius this is standard freezing ...,a
16,Fossil bones and teeth of dinosaurs have been ...,analyze new data as it becomes available,[[c analyze new data as it becomes available w...,c
17,Molly was making iced tea by putting tea bags ...,from the tea to the ice,[[b from tea to ice heres why when molly pours...,b
18,Logging companies cut trees in a forest and se...,the price of boards will increase,[[b price of boards will decrease explanation ...,a
19,It was once thought that living organisms coul...,continued experimentation.,[[d invention of microscope before invention o...,c
20,Cells take in food for energy. The part of the...,breaking down wastes,[[b breaking down wastes lysosomes are respons...,b
21,When an electric current is passed through wat...,2H_{2}O(l) -> 2H_{2}(g) + O_{2}(g),[[answer b reasoning skill identifying pros an...,b
22,Which is a fact about penguins?\nChoices: A. P...,Penguins can live in climates with freezing te...,"[[, penguins can live in climates with freezin...",a
23,A glass of water at 110Â°F is placed in a room...,73Â°F.,"[[c, c, c, c, c, boxed73, boxed73, c, c, c], [...",c
24,"Snow, rain, hail, and fog are all forms of\nCh...",water.,[[b water all forms of snow rain hail and fog ...,b
25,Scott filled a tray with juice and put it in a...,It became a solid.,[[d it became solid explanation scott filled t...,d
26,"On August 21, a flash flood warning was issued...",It is a seasonal weather feature with irregula...,[[d it is rare event inconsistent with local c...,b
27,Students heated three objects to different tem...,"Object 1, Object 3, Object 2","[[boxedb, to answer this question we need to u...",b
28,Tiny organisms called plankton live in oceans....,Plankton release oxygen.,[[c plankton release oxygen explanation plankt...,c
29,Which statement best explains why a tree branc...,Wood is buoyant.,[[wood is porous explanation reason tree branc...,b
30,Students are observing two fossils in a lab. T...,the type of environment in which the organisms...,[[d type of environment in which organisms liv...,d
31,Earth's distance from the Sun enables water to...,its ability to exist as a liquid,"[[c its ability to exist as liquid, c its abil...",c
32,Which statement correctly describes a property...,Air is a mixture of gases.,[[air is mixture of gases explanation this cho...,a
33,Which statement describes a positive effect of...,It helps explain how things work.,[[c it helps explain how things work this choi...,c
34,Which natural event occurs with the most frequ...,sunrise,"[[answer, step 1 problem explanation problem a...",a
35,A scientist maps a long region in which earthq...,Volcanism also characterizes the region.,[[c region shows extensive faulting of sedimen...,a
36,Which best describes how the sun might compare...,The sun would be tiny next to one of the large...,"[[b, b, b sun would be tiny next to one of lar...",b
37,Which statement is true about the solar system...,The solid planets are closer to the Sun.,[[b solid planets are closer to sun explanatio...,b
38,What is the main function of photosynthetic ce...,to convert energy from sunlight into food energy,[[c to convert energy from sunlight into food ...,c
39,Which of the following is the primary differen...,Hydraulic systems involve liquids and pneumati...,[[b hydraulic systems involve liquids and pneu...,b

In [71]:
accs = dftogetchal.apply(get_accc, axis = 1)
total = 0
s = 0
for i in accs:
    s = s + i[0]
    total = total + i[1]
s/total

0.4676767676767677

In [72]:
import re

def remove_non_alphanumeric_except_space(text):
    """
    Removes all characters from a string that are not alphanumeric or a space.

    Args:
        text (str): The input string.

    Returns:
        str: The string with only alphanumeric characters and spaces.
    """
    # The regex pattern `[^a-zA-Z0-9\s]+` matches one or more characters
    # that are NOT (^) lowercase letters (a-z), uppercase letters (A-Z),
    # digits (0-9), or whitespace characters (\s).
    # These matched characters are replaced with an empty string.
    cleaned_text = re.sub(r'[^a-zA-Z0-9\s]+', '', text)
    return cleaned_text

# Example usage:
input_string = "Hello, World! 123 @Python$ Program."
output_string = remove_non_alphanumeric_except_space(input_string)
print(output_string)

Hello World 123 Python Program

In [69]:
import re
import numpy as np
import pandas as pd
from collections import Counter
from itertools import chain

def _flatten(nested):
    """Recursively flatten arbitrarily nested lists/tuples."""
    for x in nested:
        if isinstance(x, (list, tuple)):
            yield from _flatten(x)
        else:
            yield x

# Compile a few regexes to robustly catch the first answer letter near the start.
# Handles:
#   "c", "b reason...", "boxedc", "boxed c", "answer b ...", "[boxedc, c, ...]"
# We ONLY accept a/b/c/d; anything else is ignored.
_PATTERNS = [
    re.compile(r'^\s*(?:boxed)?\s*([abcd])\b', re.IGNORECASE),     # "c", "boxedc", "boxed c"
    re.compile(r'^\s*answer\s*([abcd])\b', re.IGNORECASE),         # "answer b ..."
    re.compile(r'^\s*\[?\s*(?:boxed)?\s*([abcd])\b', re.IGNORECASE) # leading bracketed tokens
]

def _extract_letter(s: str):
    """Return 'a'/'b'/'c'/'d' if a clear leading vote is present, else None."""
    if not isinstance(s, str):
        s = str(s)
    s = s.strip()
    for pat in _PATTERNS:
        m = pat.search(s)
        if m:
            letter = m.group(1).lower()
            if letter in {'a','b','c','d'}:
                return letter
    # Fallback: sometimes the very first token is just 'a'/'b'/'c'/'d' with punctuation
    m = re.match(r'^([abcd])\W', s.lower())
    if m:
        return m.group(1)
    return None

def rewrites_to_percent_matrix(df: pd.DataFrame, rewrites_col='rewrite_all_ans'):
    """
    For each row, look at all strings in `rewrites_col` (list-of-lists of strings),
    tally how many indicate A/B/C/D, and return a (n_rows x 4) NumPy array of percentages.
    Order of columns: [A, B, C, D].
    """
    out = np.zeros((len(df), 4), dtype=float)
    idx_map = {'a':0, 'b':1, 'c':2, 'd':3}

    for i, rewrites in enumerate(df[rewrites_col].tolist()):
        # Flatten any nesting and keep only strings
        flat = list(_flatten(rewrites if isinstance(rewrites, (list, tuple)) else [rewrites]))
        votes = []
        for item in flat:
            letter = _extract_letter(item)
            if letter is not None:
                votes.append(letter)

        total = len(votes)
        if total > 0:
            c = Counter(votes)
            row = np.array([
                c.get('a', 0) / total,
                c.get('b', 0) / total,
                c.get('c', 0) / total,
                c.get('d', 0) / total,
            ], dtype=float)
            out[i, :] = row
        # else: leave zeros if no recognizable votes
    return out

# --- Example usage ---
# matrix = rewrites_to_percent_matrix(df_chall, 'rewrite_all_ans')
# matrix.shape  # (n_rows, 4), columns correspond to [A, B, C, D]
# matrix[0]     # e.g. array([0.5, 0.5, 0. , 0. ])

In [70]:
def convertnums(l):
    if l == 'a':
        return 0
    elif l == 'b':
        return 1
    elif l == 'c':
        return 2
    return 3

In [22]:
df_chall_percents = rewrites_to_percent_matrix(df_chall)

NameError: name 'df_chall' is not defined

In [23]:
import numpy as np

def _bin_indices(conf, n_bins=15, strategy="uniform"):
    """
    Returns bin edges and the bin index for each confidence.
    strategy: "uniform" -> equal-width bins in [0,1]
              "quantile" -> equal-count bins (uses ranks)
    """
    conf = np.asarray(conf)
    eps = 1e-12
    if strategy == "uniform":
        edges = np.linspace(0.0, 1.0, n_bins + 1)
        # place exactly-1.0 into last bin
        idx = np.minimum(np.digitize(conf, edges, right=False) - 1, n_bins - 1)
    elif strategy == "quantile":
        # quantile edges; ensure unique and covering [0,1]
        qs = np.linspace(0, 1, n_bins + 1)
        edges = np.quantile(conf, qs)
        # handle potential duplicates (e.g., many identical confidences)
        # add tiny jitter to make edges strictly increasing
        for i in range(1, len(edges)):
            if edges[i] <= edges[i-1]:
                edges[i] = np.nextafter(edges[i-1], 1.0)
        idx = np.minimum(np.digitize(conf, edges, right=False) - 1, n_bins - 1)
        idx = np.maximum(idx, 0)
    else:
        raise ValueError("strategy must be 'uniform' or 'quantile'")
    return edges, idx

def ece_binary(y_true, y_prob, n_bins=15, strategy="uniform", return_bins=False):
    """
    ECE for binary classification.
    y_true: shape (N,), values in {0,1}
    y_prob: shape (N,), predicted probability for the positive class (class=1)
    """
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob)
    assert y_true.shape == y_prob.shape

    edges, idx = _bin_indices(y_prob, n_bins, strategy)
    N = len(y_true)

    ece = 0.0
    bin_stats = []
    for b in range(n_bins):
        mask = (idx == b)
        n_b = mask.sum()
        if n_b == 0:
            bin_stats.append((b, 0, np.nan, np.nan))
            continue
        acc_b = np.mean(y_true[mask] == 1)
        conf_b = np.mean(y_prob[mask])
        ece += (n_b / N) * abs(acc_b - conf_b)
        bin_stats.append((b, n_b, acc_b, conf_b))

    if return_bins:
        # returns list of tuples: (bin_id, count, accuracy, confidence)
        return float(ece), bin_stats, edges
    return float(ece)

def ece_multiclass(y_true, y_proba, n_bins=15, strategy="uniform", return_bins=False):
    """
    ECE for multiclass classification (K classes).
    y_true: shape (N,), int labels in [0, K-1]
    y_proba: shape (N, K), row i sums to 1
    Uses the standard definition with confidence = probability of the true class.
    """
    y_true = np.asarray(y_true).astype(int)
    y_proba = np.asarray(y_proba)
    N, K = y_proba.shape
    assert y_true.shape[0] == N

    # confidence for the true class
    conf_true = y_proba[np.arange(N), y_true]
    correct = (np.argmax(y_proba, axis=1) == y_true).astype(int)

    edges, idx = _bin_indices(conf_true, n_bins, strategy)

    ece = 0.0
    bin_stats = []
    for b in range(n_bins):
        mask = (idx == b)
        n_b = mask.sum()
        if n_b == 0:
            bin_stats.append((b, 0, np.nan, np.nan))
            continue
        acc_b = np.mean(correct[mask])
        conf_b = np.mean(conf_true[mask])
        ece += (n_b / N) * abs(acc_b - conf_b)
        bin_stats.append((b, n_b, acc_b, conf_b))

    if return_bins:
        return float(ece), bin_stats, edges
    return float(ece)

# -------------------------
# Example usage
# -------------------------
if __name__ == "__main__":
    rng = np.random.default_rng(0)
    # Binary
    y = rng.integers(0, 2, size=1000)
    p = np.clip(rng.beta(2, 5, size=1000), 0, 1)
    print("Binary ECE:", ece_binary(y, p, n_bins=15, strategy="uniform"))

    # Multiclass
    N, K = 1000, 4
    logits = rng.normal(size=(N, K))
    proba = np.exp(logits) / np.exp(logits).sum(axis=1, keepdims=True)
    y_mc = rng.integers(0, K, size=N)
    print("Multiclass ECE:", ece_multiclass(y_mc, proba, n_bins=15, strategy="quantile"))

Binary ECE: 0.2908430460849268
Multiclass ECE: 0.1991652344302426

In [24]:
df_chall_percents = rewrites_to_percent_matrix(dftogetchal)
chall_correct = [convertnums(i) for i in dftogetchal['answer_letter'].values]

NameError: name 'dftogetchal' is not defined

In [25]:
df_chall_percents

NameError: name 'df_chall_percents' is not defined

In [15]:
chall_correct

NameError: name 'chall_correct' is not defined

In [16]:
ece_multiclass(chall_correct, df_chall_percents, n_bins=5)

NameError: name 'chall_correct' is not defined

In [17]:
easy_percents = rewrites_to_percent_matrix(df_easy)
easy_correct = [convertnums(i) for i in df_easy['answer_letter'].values]

NameError: name 'rewrites_to_percent_matrix' is not defined

In [317]:
ece_multiclass(easy_correct, easy_percents, n_bins=5)

0.08384960540462452

In [90]:
with open('openbookqa.json') as train_file:
    j = json.load(train_file)

In [91]:
df_QA = pd.DataFrame(j)

In [92]:
df_QA = cleandf(df_QA)

In [93]:
df_QA

,question,answer,rewrite_all_ans,answer_letter
0,A person wants to start saving money so that t...,quit eating lunch out,[[b quit eating lunch out this choice suggests...,b
1,There is most likely going to be fog around:\n...,a marsh,[[based on general climatic conditions and geo...,a
2,Predators eat\nChoices: A. lions | B. humans |...,bunnies,[[based on general knowledge of ecosystems ans...,c
3,Oak tree seeds are planted and a sidewalk is p...,parts may break the concrete,"[[b, b, roots may be split, b, roots may be sp...",c
4,An electric car runs on electricity via\nChoic...,electrical conductors,[[c electrical conductors explanation question...,c
5,As the rain forest is deforested the atmospher...,carbon,[[oxygen deforestation or clearance of forests...,c
6,an electric car contains a motor that runs on\...,ions,[[c ions explanation electric cars are powered...,c
7,The middle of the day usually involves the bri...,human planet rotation,[[b earths planet rotation explanation at sola...,b
8,The summer solstice in the northern hemisphere...,October,"[[output may, c april, , not listed in choices...",d
9,The main component in dirt is\nChoices: A. mic...,broken stones,[[d bacteria explanation main component refers...,b
10,It's easier for human's to survive in:\nChoice...,a town,[[c town in general it is considered easier fo...,c
11,A cactus stem is used to store\nChoices: A. fr...,liquid,[[based on input it seems that underlying ques...,b
12,A red-tailed hawk is searching for prey. It is...,a gecko,[[c gecko redtailed hawks are birds of prey th...,c
13,The chance of wildfires is increased by\nChoic...,parched foliage,[[parched foliage explanation parched or dry f...,a
14,A positive effect of burning biofuel is\nChoic...,powering the lights in a home,[[c powering lights in home this choice best a...,c
15,"As gasoline costs rise, alternative fuels are ...",gasoline will be needed less,[[d gasoline will be needed less explanation s...,d
16,A person wants to be able to have more natural...,panels collecting sunlight,[[c panels collecting sunlight explanation per...,c
17,A Mola Mola might live where?\nChoices: A. Lak...,Bay of Bengal,[[none as there are no options that match mola...,c
18,Which requires energy to move?\nChoices: A. we...,weasel,[[weasel explanation question asks which item ...,a
19,An animal that only eats plants is a\nChoices:...,moth,"[[herbivore, herbivore correct answer choice m...",b
20,There was a lot more water vapor in the air wh...,Hanoi,[[c baghdad explanation hanoi has tropical cli...,a
21,An example of conservation is avoiding the use...,gasoline,[[gasoline conservation typically refers to re...,a
22,What can feathers on Spheniscidae be used for?...,keeping warm,[[feathers on spheniscidae also known as pengu...,a
23,Overpopulation can cause\nChoices: A. More fre...,Lower Life Expectancy in Countries,[[b lower life expectancy in countries explana...,b
24,Shining a light through a diamond can\nChoices...,summon a brilliant wave of color,[[im happy to help you with this task based on...,b
25,If you were attacked by a shark and had to pun...,its gills,[[if you were attacked by shark and had to pun...,b
26,which of these would stop a car quicker?\nChoi...,a wheel with dry brake pads,[[d wheel with dry brake pads explanation wet ...,d
27,what system is needed for a body to get its ne...,the circulatory system,"[[circulatory system, circulatory system, circ...",a
28,Every evening a child can look into the night ...,moving upwards,[[d moving upwards this choice corresponds wit...,d
29,"When it's flying, a plane has no friction with...",ground,[[d clouds explanation question asks for eleme...,b
30,To grow plants require\nChoices: A. acid rain ...,shafts of sunlight,"[[c shafts of sunlight, c shafts of sunlight e...",c
31,What is the best way to guess a babies eye col...,The genealogy records of their family.,"[[d genealogy records of their family, d genea...",d
32,What animal eats plants?\nChoices: A. eagles |...,robins,[[none of above leopards are carnivores which ...,b
33,Which of these is a hypothesis?\nChoices: A. T...,The ice caps will completely melt if global wa...,[[ice caps will completely melt if global warm...,a
34,What explains the characteristic lunar formati...,many collisions that have occured,[[b many collisions that have occurred this ch...,b
35,Tadpoles start their lives as\nChoices: A. Wat...,Water animals,[[b frogs explanation since tadpoles are larva...,a
36,If a person puts out four apples around their ...,the apple sitting on a sunny sidewalk,[[apple sitting on sunny sidewalk according to...,a
37,What is used for sensing visual things?\nChoic...,cornea,"[[d cornea, d cornea explanation sensing visua...",d
38,They studied the soil by using\nChoices: A. pl...,a microscope,[[d microscope explanation since they studied ...,d
39,Bill's arm got cold when he put it inside the\...,refrigerator,[[refrigerator explanation word inside typical...,a

In [94]:

accs = df_QA.apply(get_accc, axis = 1)
total = 0
s = 0
for i in accs:
    s = s + i[0]
    total = total + i[1]
s/total

0.5431472081218274

In [95]:
accs

0     [49, 50]
1      [0, 50]
2     [37, 50]
3      [2, 50]
4     [28, 50]
5     [48, 50]
6     [47, 50]
7     [39, 50]
8     [21, 50]
9     [33, 50]
10     [1, 50]
11    [48, 50]
12     [4, 50]
13    [48, 50]
14    [11, 50]
15    [49, 50]
16    [50, 50]
17    [31, 40]
18    [46, 50]
19    [34, 50]
20    [37, 50]
21    [41, 50]
22    [40, 50]
23    [40, 50]
24     [3, 50]
25    [25, 50]
26     [2, 50]
27     [0, 50]
28    [36, 50]
29    [21, 40]
30    [40, 40]
31     [0, 50]
32    [48, 50]
33     [2, 50]
34     [2, 50]
35    [12, 50]
36     [1, 50]
37    [47, 50]
38    [14, 50]
39    [33, 50]
dtype: object

In [96]:
matrixqa = rewrites_to_percent_matrix(df_QA)

In [97]:
QA_correct = [convertnums(i) for i in dftogetchal['answer_letter'].values]

In [99]:
ece_multiclass(QA_correct, matrixqa, n_bins=5)

0.15635825506807238